In [ ]:
import numpy as np

from sklearn.neighbors import KNeighborsClassifier

from sklearn import datasets

In [ ]:
iris = datasets.load_iris()
iris


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
X = iris['data']
y = iris['target']
X.shape

(150, 4)

In [ ]:
# 将数据进行划分，一分为2；一部分用于训练，另一部分用于测试
index =np.arange(150)
# 将索引顺序打乱
np.random.shuffle(index)
index

array([ 61,  44, 102,  84, 121,   7,  95,  32,  86,  56,  58,  40, 146,
        22, 144,  97,  18,  35,  48,  67, 105,  68,  34,  98, 107,   1,
       115, 134, 145,  12, 148, 114,   8,  90,  29, 136,  38,   0,  83,
       133, 120,  93, 135,   4,  42, 101, 147, 125,  55,   5, 116, 131,
        49, 111,  72,  80,  63, 138, 149, 124, 122, 109,  89,  25,  37,
       113,  79,  16,  73,  94,  36, 132, 103,   9,  60,  64,  92,  81,
        10, 104,  11, 140,  69,  96, 100,  30,   6, 123,  33,  66,  87,
        28,  24,  62, 128,  91,  77, 117,  39, 137,  75, 142,  59, 126,
       139,  27, 106,  85,  47,  19,  50,   2,  21, 127,  52,  53,  41,
       130,   3, 119,  14,  54,  82,  20,  71,  65,  23,  43,  26,  99,
        15,  57, 143,  46, 118, 108,  88,  76,  17,  13,  74, 141,  78,
       110,  70,  51, 112,  31, 129,  45])

In [ ]:
# 150个数据打乱顺序100个取出来，算法学习，留下50个使用算法预测(验证算法是否可靠)
# 应用到实际中，获取现实中的数据，算法对数据进行分类
X_train,X_test = X[index[:100]],X[index[100:]]
y_train,y_test = y[index[:100]],y[index[100:]]

In [ ]:
# weights='distance'可以用来调整权重，距离越近权重越大
# p=1 曼哈顿距离 p=2 欧式距离
# n_jobs 代表采用多少进程 -1代表全部
knn = KNeighborsClassifier(n_neighbors=5,weights='distance',p=2,n_jobs=-1)

knn.fit(X_train,y_train)

y_result = knn.predict(X_test)
knn.score(X_test,y_test)

0.94

In [ ]:
# 计算概率
proba_ = knn.predict_proba(X_test)
proba_

array([[0. , 1. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 1. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 0.8, 0.2],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0.6, 0.4],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. 

In [ ]:
# 返回最大值的索引，就相当于类别
proba_.argmax(axis=1)

array([1, 2, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 1, 1, 0, 0, 1, 2, 1, 2,
       1, 1, 2, 0, 2, 0])

In [ ]:
# 对比，看算法，预测的和真实的结果，是否对应
print(y_result)
print("------------")
print(y_test)

[1 2 1 2 2 0 1 1 0 0 1 0 0 2 1 1 0 2 0 1 0 1 1 0 1 1 0 0 0 1 0 1 2 0 2 2 1
 1 0 0 1 2 1 2 1 1 2 0 2 0]
------------
[1 2 1 2 2 0 2 1 0 0 1 0 0 2 1 1 0 2 0 2 0 1 1 0 1 1 0 0 0 1 0 1 2 0 2 2 1
 1 0 0 1 2 1 2 1 1 2 0 2 0]


In [ ]:
# 求解准确率
(y_result == y_test).sum()/50

#knn.score(X_test,y_test)

0.96

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e91eb998-244f-4d4d-99b9-ff77222e7aa7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>