In [ ]:
!pip install -U opencv-python
!apt-get upgrade
!apt update && apt install -y libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx

     |████████████████████████████████| 49.9 MB 130 kB/s 
You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.




0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [301 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7,907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [15.2 kB]
Fetched 8,463 kB in 2s (5,327 kB/s)



8 packages can be upgraded. Run 'apt list --upgradable' to see them.



libfontconfig1 is already the newest version (2.13.1-2).
libfontconfig1 set to manually installed.
libsm6 is already the newest version (2:1.2.3-1).
libsm6 set to manually installed.
libxext6 is already 

In [ ]:
import pandas as pd

import numpy as np

import cv2

from sklearn.neighbors import KNeighborsClassifier

In [ ]:
target = [1,1,2,2,3,3]

In [ ]:
# i = j = 0
# path = "./data/img/{}_{}.bmp".format(i+1,j+1)
# digit = cv2.imread(path)
# digit = cv2.cvtColor(digit,code=cv2.COLOR_BGR2GRAY)
# #print(digit[:,:,0])
# # 将三维数据转会为二维
# digit = digit.reshape(204,-1)
# print(digit.shape)

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(204, 816)


In [ ]:
X = []
for i in range(3):
    for j in range(2):
        path = "./data/img/{}_{}.bmp".format(i+1,j+1)
        digit = cv2.imread(path)
        digit = cv2.cvtColor(digit,code=cv2.COLOR_BGR2GRAY)
        X.append(digit.reshape(204,-1))

In [ ]:
X = np.array(X)
X.shape

(6, 204, 272)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,target,test_size=0.1)

In [ ]:
print(X_train.shape)
X_train = X_train.reshape(5,-1)
print(X_train.shape)

(5, 204, 272)
(5, 55488)


In [ ]:

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [ ]:
path = "./data/img/test.bmp"
digit = cv2.imread(path)
digit = cv2.cvtColor(digit,code=cv2.COLOR_BGR2GRAY)

In [ ]:
digit = digit.reshape(1,-1)
digit.shape

(1, 55488)

In [ ]:
knn.predict_proba(digit)

array([[1., 0., 0.]])

In [ ]:
knn.score(X_test,y_test)

0.0

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e91eb998-244f-4d4d-99b9-ff77222e7aa7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>